[platformio]
default_envs = atoms3r_bno055

[env:atoms3r_bno055]
platform = espressif32@^6.8.1
framework = arduino
board = m5stack-atoms3
board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
monitor_speed = 115200
upload_port = /dev/ttyACM0
lib_deps = 
    m5stack/M5Unified
    throwtheswitch/Unity@^2.6.0